#                                                                        #
# Testing Settings                                                       #
#                                                                        #
# This file contains settings for various parts of the application.      #
#                                                                        #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #


TYPO3:
  FLOW3:
    persistence:
      backendOptions:
        dbname: 'flow3_functional_testing'     # adjust to your database name
        user: ''                               # adjust to your database user
        password: ''                           # adjust to your database password
